Add UTF-8 support and several changes
nimmis/docker-spigot pull request #44
Opened 2020-12-15 22:43 UTC by penut85420

Thanks to this work to let me build my server more easily, and I learn a lot from this repo!
I found that the UTF-8 character is not working under this image, and it is not friendly for server localization.
After some research, I found [a solution](https://stackoverflow.com/a/28406007) to address this issue.
So I add these to Dockerfile, and my plugins and commands with UTF-8 character finally work.

I add environment variable `$OTHER_JAVA_OPS` to let the user decide what options they want to add, such as gc collection.

due to the `output.con` will be deleted when `mc_restart`, `mc_log` will be not working, add `-F` option to `tail`.

I think that showing the logs after mc_send is unnecessary since they can simply do it by `mc_send && mc_log`, and without `mc_log` following by `mc_send`, the user can even write a script to run commands on the host.

Thanks for your work again!

2021-02-03 03:35 UTC, mmraz requested changes

2021-02-03 03:35 UTC, mmraz commented on rootfs/etc/init.d/minecraft_server
> +MC_JAVA_OPS="-Xmx$MC_MAXMEM -Xms$MC_MINMEM $OTHER_JAVA_OPS"   # java options for minecraft server
This new variable should be added to the list of ENV variables in Dockerfile similar to PR #34

2021-02-04 08:06 UTC, penut85420 commented on rootfs/etc/init.d/minecraft_server
> +MC_JAVA_OPS="-Xmx$MC_MAXMEM -Xms$MC_MINMEM $OTHER_JAVA_OPS"   # java options for minecraft server
Is this right? d9de754

2021-02-05 00:25 UTC, mmraz approved these changes

2021-02-05 00:27 UTC, mmraz commented
I merged this PR and the other outstanding PRs into my fork. mmraz/docker-spigot if you want to work with something that's being maintained.

2021-07-04 17:40 UTC, merged